In [ ]:
import numpy as np

In [ ]:
# creating array
grades = np.array([85, 90, 88, 92, 95, 80, 75, 98, 89, 83])
print(grades)

[85 90 88 92 95 80 75 98 89 83]


In [ ]:
#mean
mean = np.mean(grades)
print(mean)

87.5


In [ ]:
#median
median = np.median(grades)
print(median)

88.5


In [ ]:
#standard deviation
std = np.std(grades)
print(std)

6.591661399070799


In [ ]:
#min and max
min = np.min(grades)
print(f"min: {min}")

max = np.max(grades)
print(f"max: {max}")

min: 75
max: 98


In [ ]:
# sort grades in ascending order
sorted_grades =np.sort(grades)
print(sorted_grades)

[75 80 83 85 88 89 90 92 95 98]


In [ ]:
# index of the highest grade
max_index = np.argmax(grades)
print(f"Highest grade is at index: {max_index}")

Highest grade is at index: 7


In [ ]:
# students who scored hugher than 90
students_above_90 = np.count_nonzero(grades > 90)
print(f"Number of students who scored above 90: {students_above_90}")

Number of students who scored above 90: 3


In [ ]:
# percentage of students who scored above 90
percentage_above_90 = np.mean(grades > 90) * 100
print(f"Percentage of students who scored above 90: {percentage_above_90}%")

Percentage of students who scored above 90: 30.0%


In [ ]:
# percentage of students who scored below 75
percentage_below_75 = np.mean(grades < 75) * 100
print(f"Percentage of students who scored below 75: {percentage_below_75}%")

Percentage of students who scored below 75: 0.0%


In [ ]:
# grades above 90

high_performers = grades[grades > 90]
print(high_performers)

[92 95 98]


In [ ]:
# grades above 75
passing_grades = grades[grades > 75]
print(passing_grades)

[85 90 88 92 95 80 98 89 83]
